-- MySQL Script generated by MySQL Workbench
-- 10/22/18 19:38:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Adminstrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Adminstrator` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Service` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organizations` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `Service_idService` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Organizations_Service1_idx` (`Service_idService` ASC),
  CONSTRAINT `fk_Organizations_Service1`
    FOREIGN KEY (`Service_idService`)
    REFERENCES `mydb`.`Service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `pay_amount` VARCHAR(45) NULL,
  `organizations_id` INT NULL,
  `Service_idService` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Customer_Service1_idx` (`Service_idService` ASC),
  CONSTRAINT `fk_Customer_Service1`
    FOREIGN KEY (`Service_idService`)
    REFERENCES `mydb`.`Service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lisence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lisence` (
  `idLisence` INT NOT NULL,
  `Organizations_id` INT NOT NULL,
  `Adminstrator_id` INT NOT NULL,
  PRIMARY KEY (`idLisence`),
  INDEX `fk_Lisence_Organizations1_idx` (`Organizations_id` ASC),
  INDEX `fk_Lisence_Adminstrator1_idx` (`Adminstrator_id` ASC),
  CONSTRAINT `fk_Lisence_Organizations1`
    FOREIGN KEY (`Organizations_id`)
    REFERENCES `mydb`.`Organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lisence_Adminstrator1`
    FOREIGN KEY (`Adminstrator_id`)
    REFERENCES `mydb`.`Adminstrator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bill` (
  `idBill` INT NOT NULL,
  `Organizations_id` INT NOT NULL,
  `Customer_id` INT NOT NULL,
  PRIMARY KEY (`idBill`),
  INDEX `fk_Bill_Organizations1_idx` (`Organizations_id` ASC),
  INDEX `fk_Bill_Customer1_idx` (`Customer_id` ASC),
  CONSTRAINT `fk_Bill_Organizations1`
    FOREIGN KEY (`Organizations_id`)
    REFERENCES `mydb`.`Organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bill_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `mydb`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tax` (
  `id` INT NOT NULL,
  `object_id` VARCHAR(45) NULL,
  `tax_type` VARCHAR(45) NULL,
  `tax_amount` VARCHAR(45) NULL,
  `start-date` VARCHAR(45) NULL,
  `end_date` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`peson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`peson` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `mobile_id` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `role_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owners` (
  `id` INT NOT NULL,
  `person_id` VARCHAR(45) NULL,
  `business_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `id` INT NOT NULL,
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Business_Organizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Business_Organizations` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `license_id` VARCHAR(45) NULL,
  `tax_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tax` (
  `id` INT NOT NULL,
  `object_id` VARCHAR(45) NULL,
  `tax_type` VARCHAR(45) NULL,
  `tax_amount` VARCHAR(45) NULL,
  `start-date` VARCHAR(45) NULL,
  `end_date` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Authority_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Authority_action` (
  `id` INT NOT NULL,
  `business_id` VARCHAR(45) NULL,
  `liscense_id` VARCHAR(45) NULL,
  `tax_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`License`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`License` (
  `id` INT NOT NULL,
  `start_date` VARCHAR(45) NULL,
  `end_date` VARCHAR(45) NULL,
  `payment` VARCHAR(45) NULL,
  `business_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cash_memo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cash_memo` (
  `bill_id` INT NOT NULL,
  `business_id` INT NULL,
  `CustomerName` VARCHAR(45) NULL,
  `product_list_id` VARCHAR(45) NULL,
  `total_amount` VARCHAR(45) NULL,
  PRIMARY KEY (`bill_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `amount` DOUBLE NULL,
  `perunit_price` DOUBLE NULL,
  `total_price` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_list` (
  `id` INT NOT NULL,
  `cash_memo_id` INT NULL,
  `product_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
